### PR TITLE
Fixing code 403 issue when using cookies 

### PR DESCRIPTION
**Pull request by XM4ZE**

### CODE REVIEW

**Comment by warren-bank** [comment]
You, sir, are my hero! This PR fixes [an issue](https://github.com/warren-bank/browser-ytdl-core/issues/1) that I've been wrestling with.

**Comment by deepfaith** [comment]
Kindly merge this. MinigetError: Status code: 403 persists at all times

**Comment by warren-bank** [comment]
@DmitryKravchenkoWizard
I'm curious.. when you test this patch, are the URLs for all available formats now working?
I find that only `itag: 18` returns 200.. and all others still return a 403.

**Comment by xMiyuka** [comment]
I can confirm this works for me. Yes, only itag: 18 work but if this is for a discord bot this should be plenty fine. What I did was obviously use the fix above, then goto @distube/youtube/dist/index.js and add the following on lines 118

` 
    let info = await import_ytdl_core.default.getInfo(song.url, this.ytdlOptions);
    info.formats = info.formats.filter((f) => f.hasAudio && f.itag == 18); //this is to ensure only 18 is trying to be loaded
`

**Comment by warren-bank** [comment]
ok.. so I'm not alone, you're confirming that only `itag: 18` is working for you, as well.
good to know, thanks.

**Comment by DmitryKravchenkoWizard** [comment]
> @DmitryKravchenkoWizard I'm curious.. when you test this patch, are the URLs for all available formats now working? I find that only `itag: 18` returns 200.. and all others still return a 403. My use-case is the definition of edge.. so it's possible that I'm alone on that.. dunno.

For my code:
async downloadFromYoutube(url: string, cookies: Cookie[], uploadToAzure: boolean = false): Promise<string> {
    try {
      const agent = ytdl.createAgent(cookies);
      const videoStream = await ytdl(url, {
        quality: 'highest', // or 'highestvideo' for video and 'highestaudio' for audio separately
        filter: format => {
          return format.container === 'mp4' && format.hasAudio && format.hasVideo // Confirm that video and audio download together
        },
        agent
      });
      const fileName = `${Date.now()}.mp4`;
      await this.writeVideoStreamToFile(videoStream, fileName, uploadToAzure);

      return fileName
    } catch (error) {
      console.log('error downloadFromYoutube', error);
      throw error
    }
  }
  This fix also help to exclude 403 error

**Pull request closed without merging**
